import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { Footer } from "@/components/footer";
import { WebVitals } from "@/components/web-vitals";
import "./globals.css";

const workSans = Work_Sans({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "InsightEdge",
  description: "Generated by create next app",
};

// export function reportWebVitals(metric: NextWebVitalsMetric) {
//   if (typeof window === "undefined") return;

//   const allowedMetrics = ['LCP', 'FID', 'CLS'];

//   if (allowedMetrics.includes(metric.name)) {
//     console.log(`[Web Vital] ${metric.name}: `, metric.value);
//     import("@/lib/storeVitalsInLocalStorage").then((mod) => {
//       mod.storeWebVital(metric);
//     });
//   }
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${workSans.className} antialiased`}
      >
        <WebVitals />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <SidebarProvider defaultOpen={false}>
              <AppSidebar />
              <div className="w-full">
                <header>
                  <Navbar />
                </header>
                {children}
                <Toaster position="top-right" />
                <Footer />
              </div>
            </SidebarProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
